# Data PreProcessing

## Loading the Dataset

In [1]:
import pandas as pd

In [2]:
df_churn=pd.read_csv("Churn_Clean.csv")
df=df_churn.copy()

The Data is Already Cleaned.
Here we are going to process the data for our Machine Learning Model

## Dropping Irrelevant Columns

In [3]:
df=df.drop("CustomerID",axis=1)

“The customerID column is removed because it is a unique identifier and does not provide any predictive information for churn analysis.”

In [4]:
df=df.drop("Count",axis=1)

“The Count column is dropped because it contains the same value for all rows and does not provide any useful information for churn analysis.”

In [5]:
df=df.drop("Lat Long",axis=1)

In [6]:
df=df.drop("Latitude",axis=1)

In [7]:
df=df.drop("Longitude",axis=1)

“The Latitude and Longitude columns are dropped as they are unique for each customer and do not provide useful information for predicting churn.”

In [8]:
df=df.drop("Tenure_Group",axis=1)

In [9]:
df=df.drop("Monthly_Groups",axis=1)

“The Tenure_Group and Monthly_Group columns, created for EDA, are dropped before ML preprocessing as they are not original features.”

In [10]:
df.columns

Index(['Country', 'State', 'City', 'Zip Code', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason'],
      dtype='object')

In [11]:
df.head()

,Country,State,City,Zip Code,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,United States,California,Los Angeles,90003,Male,No,No,No,2,Yes,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,United States,California,Los Angeles,90005,Female,No,No,Yes,2,Yes,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,United States,California,Los Angeles,90006,Female,No,No,Yes,8,Yes,...,Month-to-month,Yes,Electronic check,99.65,820.50,Yes,1,86,5372,Moved
3,United States,California,Los Angeles,90010,Female,No,Yes,Yes,28,Yes,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,United States,California,Los Angeles,90015,Male,No,No,Yes,49,Yes,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes,1,89,5340,Competitor had better devices

## Label Encoding

In [12]:
binary_col=[col for col in df.columns if df[col].nunique()==2]
print(binary_col)

['Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Phone Service', 'Paperless Billing', 'Churn Label', 'Churn Value']

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
le=LabelEncoder()

In [15]:
for col in binary_col:
    df[col]=le.fit_transform(df[col])

In [16]:
df[binary_col].head()

,Gender,Senior Citizen,Partner,Dependents,Phone Service,Paperless Billing,Churn Label,Churn Value
0,1,0,0,0,1,1,1,1
1,0,0,0,1,1,1,1,1
2,0,0,0,1,1,1,1,1
3,0,0,1,1,1,1,1,1
4,1,0,0,1,1,1,1,1

All binary categorical columns (columns with only two unique values) were converted into numeric form using Label Encoding.

## One-Hot Encoding

In [17]:
multi_class_col=[col for col in df.columns if df[col].nunique()>2]
print(multi_class_col)

['City', 'Zip Code', 'Tenure Months', 'Multiple Lines', 'Internet Service', 'Online Security', 'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV', 'Streaming Movies', 'Contract', 'Payment Method', 'Monthly Charges', 'Total Charges', 'Churn Score', 'CLTV', 'Churn Reason']

In [18]:
three_class=[col for col in df.columns if df[col].nunique()==3]
print(three_class)

['Multiple Lines', 'Internet Service', 'Online Security', 'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV', 'Streaming Movies', 'Contract']

In [19]:
df['Payment Method'].nunique()

4

In [20]:
multi_col=['Multiple Lines','Internet Service','Online Security','Online Backup','Device Protection','Tech Support','Streaming TV','Streaming Movies',
          'Contract','Payment Method']

for col in multi_col:
    if col not in multi_col:
        print(f"Column not found:{col}")
        
df=pd.get_dummies(df,columns=multi_col,drop_first=True)

In [21]:
df.columns

Index(['Country', 'State', 'City', 'Zip Code', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Paperless Billing', 'Monthly Charges', 'Total Charges', 'Churn Label',
       'Churn Value', 'Churn Score', 'CLTV', 'Churn Reason',
       'Multiple Lines_No phone service', 'Multiple Lines_Yes',
       'Internet Service_Fiber optic', 'Internet Service_No',
       'Online Security_No internet service', 'Online Security_Yes',
       'Online Backup_No internet service', 'Online Backup_Yes',
       'Device Protection_No internet service', 'Device Protection_Yes',
       'Tech Support_No internet service', 'Tech Support_Yes',
       'Streaming TV_No internet service', 'Streaming TV_Yes',
       'Streaming Movies_No internet service', 'Streaming Movies_Yes',
       'Contract_One year', 'Contract_Two year',
       'Payment Method_Credit card (automatic)',
       'Payment Method_Electronic check', 'Payment Method_Mailed check'],
      dtype='object')

In [22]:
df.head()

,Country,State,City,Zip Code,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,...,Tech Support_Yes,Streaming TV_No internet service,Streaming TV_Yes,Streaming Movies_No internet service,Streaming Movies_Yes,Contract_One year,Contract_Two year,Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check
0,United States,California,Los Angeles,90003,1,0,0,0,2,1,...,False,False,False,False,False,False,False,False,False,True
1,United States,California,Los Angeles,90005,0,0,0,1,2,1,...,False,False,False,False,False,False,False,False,True,False
2,United States,California,Los Angeles,90006,0,0,0,1,8,1,...,False,False,True,False,True,False,False,False,True,False
3,United States,California,Los Angeles,90010,0,0,1,1,28,1,...,True,False,True,False,True,False,False,False,True,False
4,United States,California,Los Angeles,90015,1,0,0,1,49,1,...,False,False,True,False,True,False,False,False,False,False

In [24]:
df.dtypes

Country                                    object
State                                      object
City                                       object
Zip Code                                    int64
Gender                                      int64
Senior Citizen                              int64
Partner                                     int64
Dependents                                  int64
Tenure Months                               int64
Phone Service                               int64
Paperless Billing                           int64
Monthly Charges                           float64
Total Charges                             float64
Churn Label                                 int64
Churn Value                                 int64
Churn Score                                 int64
CLTV                                        int64
Churn Reason                               object
Multiple Lines_No phone service              bool
Multiple Lines_Yes                           bool
Internet Service_Fiber optic                 bool
Internet Service_No                          bool
Online Security_No internet service          bool
Online Security_Yes                          bool
Online Backup_No internet service            bool
Online Backup_Yes                            bool
Device Protection_No internet service        bool
Device Protection_Yes                        bool
Tech Support_No internet service             bool
Tech Support_Yes                             bool
Streaming TV_No internet service             bool
Streaming TV_Yes                             bool
Streaming Movies_No internet service         bool
Streaming Movies_Yes                         bool
Contract_One year                            bool
Contract_Two year                            bool
Payment Method_Credit card (automatic)       bool
Payment Method_Electronic check              bool
Payment Method_Mailed check                  bool
dtype: object

In [25]:
bool_col=[col for col in df.columns if(df[col].dtype==bool)]
print(bool_col)

['Multiple Lines_No phone service', 'Multiple Lines_Yes', 'Internet Service_Fiber optic', 'Internet Service_No', 'Online Security_No internet service', 'Online Security_Yes', 'Online Backup_No internet service', 'Online Backup_Yes', 'Device Protection_No internet service', 'Device Protection_Yes', 'Tech Support_No internet service', 'Tech Support_Yes', 'Streaming TV_No internet service', 'Streaming TV_Yes', 'Streaming Movies_No internet service', 'Streaming Movies_Yes', 'Contract_One year', 'Contract_Two year', 'Payment Method_Credit card (automatic)', 'Payment Method_Electronic check', 'Payment Method_Mailed check']

In [26]:
for col in bool_col:
    df[col]=df[col].astype(int)

In [27]:
df.dtypes

Country                                    object
State                                      object
City                                       object
Zip Code                                    int64
Gender                                      int64
Senior Citizen                              int64
Partner                                     int64
Dependents                                  int64
Tenure Months                               int64
Phone Service                               int64
Paperless Billing                           int64
Monthly Charges                           float64
Total Charges                             float64
Churn Label                                 int64
Churn Value                                 int64
Churn Score                                 int64
CLTV                                        int64
Churn Reason                               object
Multiple Lines_No phone service             int64
Multiple Lines_Yes                          int64
Internet Service_Fiber optic                int64
Internet Service_No                         int64
Online Security_No internet service         int64
Online Security_Yes                         int64
Online Backup_No internet service           int64
Online Backup_Yes                           int64
Device Protection_No internet service       int64
Device Protection_Yes                       int64
Tech Support_No internet service            int64
Tech Support_Yes                            int64
Streaming TV_No internet service            int64
Streaming TV_Yes                            int64
Streaming Movies_No internet service        int64
Streaming Movies_Yes                        int64
Contract_One year                           int64
Contract_Two year                           int64
Payment Method_Credit card (automatic)      int64
Payment Method_Electronic check             int64
Payment Method_Mailed check                 int64
dtype: object

In [29]:
df.isnull().sum()

Country                                    0
State                                      0
City                                       0
Zip Code                                   0
Gender                                     0
Senior Citizen                             0
Partner                                    0
Dependents                                 0
Tenure Months                              0
Phone Service                              0
Paperless Billing                          0
Monthly Charges                            0
Total Charges                             11
Churn Label                                0
Churn Value                                0
Churn Score                                0
CLTV                                       0
Churn Reason                               0
Multiple Lines_No phone service            0
Multiple Lines_Yes                         0
Internet Service_Fiber optic               0
Internet Service_No                        0
Online Security_No internet service        0
Online Security_Yes                        0
Online Backup_No internet service          0
Online Backup_Yes                          0
Device Protection_No internet service      0
Device Protection_Yes                      0
Tech Support_No internet service           0
Tech Support_Yes                           0
Streaming TV_No internet service           0
Streaming TV_Yes                           0
Streaming Movies_No internet service       0
Streaming Movies_Yes                       0
Contract_One year                          0
Contract_Two year                          0
Payment Method_Credit card (automatic)     0
Payment Method_Electronic check            0
Payment Method_Mailed check                0
dtype: int64

In [30]:
df['Total Charges']=df['Total Charges'].fillna(df['Total Charges'].median())

In [31]:
df.isnull().sum()

Country                                   0
State                                     0
City                                      0
Zip Code                                  0
Gender                                    0
Senior Citizen                            0
Partner                                   0
Dependents                                0
Tenure Months                             0
Phone Service                             0
Paperless Billing                         0
Monthly Charges                           0
Total Charges                             0
Churn Label                               0
Churn Value                               0
Churn Score                               0
CLTV                                      0
Churn Reason                              0
Multiple Lines_No phone service           0
Multiple Lines_Yes                        0
Internet Service_Fiber optic              0
Internet Service_No                       0
Online Security_No internet service       0
Online Security_Yes                       0
Online Backup_No internet service         0
Online Backup_Yes                         0
Device Protection_No internet service     0
Device Protection_Yes                     0
Tech Support_No internet service          0
Tech Support_Yes                          0
Streaming TV_No internet service          0
Streaming TV_Yes                          0
Streaming Movies_No internet service      0
Streaming Movies_Yes                      0
Contract_One year                         0
Contract_Two year                         0
Payment Method_Credit card (automatic)    0
Payment Method_Electronic check           0
Payment Method_Mailed check               0
dtype: int64

In [32]:
df.to_csv("Churn_Processed.csv",index=False)